from fastapi import APIRouter

router = APIRouter()

SAMPLE_QUERIES = [
    {
        "id": 1,
        "question": "Which out-of-stock products have the highest estimated revenue?",
        "category": "Inventory Analytics",
        "description": "Demonstrates JOIN across products, categories, and order_items with WHERE stock_quantity = 0 and GROUP BY."
    },
    {
        "id": 2,
        "question": "Who are the top 5 customers by total spending?",
        "category": "Customer Analytics",
        "description": "Aggregates total customer order revenue with ORDER BY and LIMIT 5."
    },
    {
        "id": 3,
        "question": "What is the total revenue generated by each product category?",
        "category": "Category Performance",
        "description": "Joins categories, products, order_items, and orders to compute sales volume by category."
    },
    {
        "id": 4,
        "question": "Show monthly order count and total sales trends.",
        "category": "Time Series",
        "description": "Groups orders by date/month to plot trend lines."
    },
    {
        "id": 5,
        "question": "Which products need to be reordered soon (stock <= reorder level)?",
        "category": "Supply Chain",
        "description": "Filters products based on reorder thresholds."
    }
]


@router.get("/sample-queries", summary="Get Pre-configured Sample Questions")
def get_sample_queries():
    """Returns list of curated analytical questions for instant UI testing."""
    return {"sample_queries": SAMPLE_QUERIES}
